import { Dimensions, StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    globalMargin:{
        marginHorizontal: 20,
    },
    title:{
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 10,
    },
    botonGrande:{
        backgroundColor: '#00a680',
        padding: 10,
        borderRadius: 5,
        marginBottom: 10,
        marginRight: 10,
    },
    botonGrandeTexto:{
        color: 'white',
        fontSize: 20,
        fontWeight: 'bold',
    },
    Logo:{
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 10,
    },
    avatarContainer:{  
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    menuContainer:{
        marginBottom: 20,
        marginVertical: 20,
        marginHorizontal: 20,
        marginTop: 20,
        borderRadius: 5,
        height: 500,
        alignItems: 'center',
        backgroundColor: 'white',
        borderWidth: 2,
        borderColor: '#00a680',
    },
    menuTexto:{
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
    },
    menuBotones:{
        marginTop: 50,
        marginBottom: 50,
        backgroundColor: '#6788a8',
        borderRadius: 20,
        height: 52,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'white',
        borderWidth: 1,
        paddingHorizontal: 20,
        paddingVertical: 10,
    },
    imagePoster:{
        width: '100%',
        height: 700,
    },
    channelData:{
        marginBottom: 20,
    },
    feedData:{
        marginBottom: 20,      
    },
    feedDataText:{
        fontSize: 20,
        fontWeight: 'bold',
    },
});

export const loginStyles = StyleSheet.create({
    container: {
        flex: 1,

        justifyContent: 'center',
        paddingHorizontal: 30,
        height: 600,
        marginBottom: 50
    },
    title: {
        fontSize: 30,
        fontWeight: 'bold',
        marginBottom: 20,
        color: 'white',
    },
    logo: {
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 10,
    },
    logoImg: {
        width: '100%',
        height: '100%',
        borderRadius: 50,
    },
    avatarContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    avatar: {
        width: 100,
        height: 100,
        borderRadius: 50,
    },
    form: {
        marginBottom: 20,
        marginHorizontal: 20,
    },
    label: {
        fontSize: 18,
        marginBottom: 25,
        color: 'white',
    },
    input: {
        height:  40,
        fontSize: 15,
        color: 'white',
        borderBottomColor: (Platform.OS === 'ios') ? 'white' : 'transparent',
        borderBottomWidth: (Platform.OS === 'ios') ? 1 : 0,
        marginBottom: 20,
        paddingBottom: 4,
    },
    button: {
        marginHorizontal: 20,
        backgroundColor: '#6788a8',
        borderRadius: 100,
        height: 52,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'white',
        borderWidth: 1,
        paddingHorizontal: 20,
        paddingVertical: 10,
    },
    buttonContainer: {
        marginTop: 20,
        alignItems: 'center',
    },
    buttonText: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#fff',
    },
});

export const registerStyles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: 30,
        marginTop: 70,
        height: 600,
        marginBottom: 50
    },
    title: {
        fontSize: 30,
        fontWeight: 'bold',
        marginBottom: 20,
        color: '#6788a8',
    },
    logo: {
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 10,
    },
    logoImg: {
        width: '100%',
        height: '100%',
        borderRadius: 50,
    },
    avatarContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    avatar: {
        width: 100,
        height: 100,
        borderRadius: 50,
    },
    form: {
        marginBottom: 20,
        marginHorizontal: 20,
    },
    label: {
        fontSize: 18,
        marginBottom: 25,
        color: '#6788a8',
    },
    input: {
        borderBottomColor: (Platform.OS === 'ios') ? '#8A8F9E': 'transparent',
        borderBottomWidth: (Platform.OS === 'ios') ? StyleSheet.hairlineWidth : 0,
        height: 40,
        fontSize: 15,
        color: '#6788a8',
        marginBottom: 20,
        paddingBottom: 4
    },
    button: {
        marginHorizontal: 20,
        backgroundColor: '#6788a8',
        borderRadius: 100,
        height: 52,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'white',
        borderWidth: 1,
        paddingHorizontal: 20,
        paddingVertical: 10,
    },
    buttonContainer: {
        marginTop: 20,
        alignItems: 'center',
    },
    buttonText: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#fff',
    },
    buttonReturn: {
        marginTop: 20,
        marginBottom: 20,
        backgroundColor: '#6788a8',
        borderRadius: 100,
        height: 52,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'white',
        borderWidth: 1,
        paddingHorizontal: 20,
        paddingVertical: 10,
    },
});

export const ContactStyles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: 30,
        height: 600,
        marginBottom: 50,
    },
    title: {
        fontSize: 30,
        fontWeight: 'bold',
        marginBottom: 20,
        color: '#6788a8',
    },
    avatarContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    avatar: {
        width: 200,
        height: 200,
        borderRadius: 100,
    },
    button: {
        marginHorizontal: 20,
        backgroundColor: '#6788a8',
        borderRadius: 100,
        height: 52,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'white',
        borderWidth: 1,
        paddingHorizontal: 20,
        paddingVertical: 10,
    },
    buttonContainer: {
        marginTop: 20,
        alignItems: 'center',
    },
    buttonText: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#fff',
    },
    text: {
        fontSize: 18,
        marginBottom: 25,
        color: '#6788a8',
    },
    infoContainer: {
        width: 350,
        height: 290,
        backgroundColor: '#fff',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#6788a8',
    },
    
});

export const DataStyles = StyleSheet.create({
    globalMargin:{
        marginHorizontal: 20,
        marginVertical: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    container:{
        alignItems:'center',
        flex:1,
        marginBottom:20,
        marginLeft:20,
        flexDirection:'column'
    },
    title:{
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
        alignSelf: 'center',
        textAlign: 'center',
    },
    title_map:{
        fontSize: 20,
        fontWeight: 'bold',
        color: '#6788a8',
        alignSelf: 'center',
        textAlign: 'center',
    },
    channelData:{
        marginBottom: 20,
        marginLeft: 10,
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    containerDistance:{
        width: 290,
        height: 90,
        marginRight: 20,
        marginTop: 20,
        borderRadius: 10,
        backgroundColor: '#6788a8',
        marginBottom: 20,
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'center'
    },
    feedData1:{
        justifyContent:'center',
        flex:1,
        flexDirection:'row',
        marginBottom:10,
        marginLeft:50,
        marginRight:10,
    },
    feedData2:{
        justifyContent:'center',
        flex:1,
        flexDirection:'row',
        marginBottom:10,
        marginLeft:50,
        marginRight:10,
    },
    feedDataText:{
        alignSelf: 'center',
        fontWeight: 'bold',
        color: 'white',
        fontSize: 15,
    },
    tempContainer:{
        width: 140,
        height: 140,
        borderRadius: 20,
        backgroundColor: 'powderblue',
        justifyContent:'center',
        alignItems:'center',
        margin:10,
        alignSelf:'center',
        borderWidth: 1,
        borderColor: '#6788a8',
    },
    humContainer:{
        width: 140,
        height: 140,
        borderRadius: 20,
        backgroundColor: 'skyblue',
        justifyContent:'center',
        alignItems:'center',
        margin:10,
        alignSelf:'center',
        borderWidth: 1,
        borderColor: '#6788a8',
    },
    aguContainer:{
        width: 140,
        height: 140,
        borderRadius: 20,
        backgroundColor: 'steelblue',
        justifyContent:'center',
        alignItems:'center',
        margin:10,
        alignSelf:'center',
        borderWidth: 1,
        borderColor: '#6788a8',
    },
    vieContainer:{
        width: 140,
        height: 140,
        borderRadius: 20,
        backgroundColor: 'slateblue',
        justifyContent:'center',
        alignItems:'center',
        margin:10,
        alignSelf:'center',
        borderWidth: 1,
        borderColor: '#6788a8',
    },
    container_map:{
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        margin: 10,
        alignSelf:'center',
        borderWidth: 1,
        borderColor: '#6788a8',
    },
    map: {
        width: 350,
        height: 290,
    },
    marker: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#6788a8',
        alignItems: 'center',
        justifyContent: 'center',
    },
    
});

export const SettingStyles = StyleSheet.create({
    container: {
        flex: 1,
        paddingHorizontal: 30,
        height: 600,
        marginBottom: 50,
    },
    title: {
        fontSize: 30,
        fontWeight: 'bold',
        marginBottom: 20,
        color: '#6788a8',
    },  
    button: {
        marginHorizontal: 20,
        backgroundColor: '#6788a8',
        borderRadius: 100,
        height: 52,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'white',
        borderWidth: 1,
        paddingHorizontal: 20,
        paddingVertical: 10,
    },
    buttonContainer: {
        marginTop: 20,
        alignItems: 'center',
    },
    buttonText: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#fff',
    },
    text: {
        fontSize: 18,
        marginBottom: 25,
        color: '#6788a8',
    },
    infoContainer: {
        width: 350,
        height: 290,
        backgroundColor: '#fff',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#6788a8',
    },
});